package pojos;
// Generated Aug 7, 2022 2:45:21 PM by Hibernate Tools 4.3.1



/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private String id;
     private String pname;
     private String description;
     private int barcode;
     private float cprice;
     private float rprice;
     private int qty;
     private int rlevel;

    public Product() {
    }

    public Product(String id, String pname, String description, int barcode, float cprice, float rprice, int qty, int rlevel) {
       this.id = id;
       this.pname = pname;
       this.description = description;
       this.barcode = barcode;
       this.cprice = cprice;
       this.rprice = rprice;
       this.qty = qty;
       this.rlevel = rlevel;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getPname() {
        return this.pname;
    }
    
    public void setPname(String pname) {
        this.pname = pname;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public int getBarcode() {
        return this.barcode;
    }
    
    public void setBarcode(int barcode) {
        this.barcode = barcode;
    }
    public float getCprice() {
        return this.cprice;
    }
    
    public void setCprice(float cprice) {
        this.cprice = cprice;
    }
    public float getRprice() {
        return this.rprice;
    }
    
    public void setRprice(float rprice) {
        this.rprice = rprice;
    }
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }
    public int getRlevel() {
        return this.rlevel;
    }
    
    public void setRlevel(int rlevel) {
        this.rlevel = rlevel;
    }




}


