package pojos;
// Generated Aug 7, 2022 2:45:21 PM by Hibernate Tools 4.3.1



/**
 * Purchaseitem generated by hbm2java
 */
public class Purchaseitem  implements java.io.Serializable {


     private Integer id;
     private int purid;
     private int pid;
     private int rprice;
     private int qty;
     private int total;

    public Purchaseitem() {
    }

    public Purchaseitem(int purid, int pid, int rprice, int qty, int total) {
       this.purid = purid;
       this.pid = pid;
       this.rprice = rprice;
       this.qty = qty;
       this.total = total;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getPurid() {
        return this.purid;
    }
    
    public void setPurid(int purid) {
        this.purid = purid;
    }
    public int getPid() {
        return this.pid;
    }
    
    public void setPid(int pid) {
        this.pid = pid;
    }
    public int getRprice() {
        return this.rprice;
    }
    
    public void setRprice(int rprice) {
        this.rprice = rprice;
    }
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }
    public int getTotal() {
        return this.total;
    }
    
    public void setTotal(int total) {
        this.total = total;
    }




}


