package pojos;
// Generated Aug 7, 2022 2:45:21 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Purchase generated by hbm2java
 */
public class Purchase  implements java.io.Serializable {


     private Integer id;
     private Date date;
     private String vendor;
     private float subtotal;
     private float pay;
     private float bal;

    public Purchase() {
    }

    public Purchase(Date date, String vendor, float subtotal, float pay, float bal) {
       this.date = date;
       this.vendor = vendor;
       this.subtotal = subtotal;
       this.pay = pay;
       this.bal = bal;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getVendor() {
        return this.vendor;
    }
    
    public void setVendor(String vendor) {
        this.vendor = vendor;
    }
    public float getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(float subtotal) {
        this.subtotal = subtotal;
    }
    public float getPay() {
        return this.pay;
    }
    
    public void setPay(float pay) {
        this.pay = pay;
    }
    public float getBal() {
        return this.bal;
    }
    
    public void setBal(float bal) {
        this.bal = bal;
    }




}


