package pojos;
// Generated Aug 7, 2022 2:45:21 PM by Hibernate Tools 4.3.1



/**
 * SalesProduct generated by hbm2java
 */
public class SalesProduct  implements java.io.Serializable {


     private Integer id;
     private int salesId;
     private int pid;
     private float price;
     private int qty;
     private float total;

    public SalesProduct() {
    }

    public SalesProduct(int salesId, int pid, float price, int qty, float total) {
       this.salesId = salesId;
       this.pid = pid;
       this.price = price;
       this.qty = qty;
       this.total = total;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getSalesId() {
        return this.salesId;
    }
    
    public void setSalesId(int salesId) {
        this.salesId = salesId;
    }
    public int getPid() {
        return this.pid;
    }
    
    public void setPid(int pid) {
        this.pid = pid;
    }
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }
    public float getTotal() {
        return this.total;
    }
    
    public void setTotal(float total) {
        this.total = total;
    }




}


