package pojos;
// Generated Aug 7, 2022 2:45:21 PM by Hibernate Tools 4.3.1



/**
 * Signup generated by hbm2java
 */
public class Signup  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String email;
     private String username;
     private String password;

    public Signup() {
    }

    public Signup(String name, String email, String username, String password) {
       this.name = name;
       this.email = email;
       this.username = username;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


