/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stock;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MSI
 */
public class product extends javax.swing.JFrame {

    /**
     * Creates new form product
     */
    public product() {
        initComponents();
        Connect();
        load();
        autoID();
         jButton2.setEnabled(true);
        jButton1.setEnabled(false);
        jButton4.setEnabled(false);
      
        
    }
    Connection con;
    PreparedStatement pst;
    DefaultTableModel df;
    
    public void autoID(){
        try {
            Statement s=con.createStatement();
            ResultSet rs=s.executeQuery("select MAX(id) from product");
            rs.next();
            rs.getString("Max(id)");
            
            if(rs.getString ("Max(id)")== null)
            {
                id2.setText("P0001");
               
            }
            else{
                long id = Long.parseLong(rs.getString("Max(id)").substring(2,rs.getString("Max(id"
                        + ")").length()));
                id++;
                id2.setText("P0"+String.format("%03d", id));
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(vendor.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    
    public void Connect(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/stockmanagement","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(vendor.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(vendor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void load(){
        
        int a;
        try {
            pst=con.prepareStatement("select * from product");
            ResultSet rs =pst.executeQuery();
            
            ResultSetMetaData rd=rs.getMetaData();
            a= rd.getColumnCount();
            df=(DefaultTableModel)jTable1.getModel();
            df.setRowCount(0);
            
            while(rs.next())
            {
                Vector v2=new Vector();
                for(int i=1; i<=a; i  ++)
                {
                    v2.add(rs.getString("id"));
                     v2.add(rs.getString("pname"));
                      v2.add(rs.getString("description"));
                       v2.add(rs.getString("barcode"));
                       v2.add(rs.getString("cprice"));
                       v2.add(rs.getString("rprice"));
                       v2.add(rs.getString("qty"));
                       v2.add(rs.getString("rlevel"));
                }
                df.addRow(v2);
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(vendor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtpname = new javax.swing.JTextField();
        txtdes = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtbarcode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtcprice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtrprice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtqty = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtlevel = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        searchbtn = new javax.swing.JButton();
        id2 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        ProductID = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PRODUCT");

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Product Name");

        txtpname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtpname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpnameActionPerformed(evt);
            }
        });

        txtdes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtdes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdesActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Description");

        txtbarcode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtbarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbarcodeActionPerformed(evt);
            }
        });
        txtbarcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbarcodeKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Barcode");

        txtcprice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtcprice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtcpriceMouseReleased(evt);
            }
        });
        txtcprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcpriceActionPerformed(evt);
            }
        });
        txtcprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcpriceKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Cost Price");

        txtrprice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtrprice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtrpriceMouseReleased(evt);
            }
        });
        txtrprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrpriceActionPerformed(evt);
            }
        });
        txtrprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtrpriceKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Retail Price");

        txtqty.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqtyActionPerformed(evt);
            }
        });
        txtqty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtqtyKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Qty");

        txtlevel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtlevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlevelActionPerformed(evt);
            }
        });
        txtlevel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtlevelKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("ReOderLevel");

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Edit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ProductID", "ProductName", "Description", "Barcode", "CostPrice", "RetailPrice", "Qty", "RLevel "
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        searchbtn.setBackground(new java.awt.Color(0, 0, 0));
        searchbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchbtn.setForeground(new java.awt.Color(255, 255, 255));
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        id2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txtsearch.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });

        ProductID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ProductID.setText("ProductID");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchbtn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(40, 40, 40))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtlevel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtqty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtrprice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcprice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtbarcode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProductID)
                            .addComponent(id2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpname, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtbarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtcprice, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtrprice, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtlevel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jButton5.setBackground(new java.awt.Color(255, 51, 51));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Close");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(70, 70, 70))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        String PId =txtsearch.getText();
        try{

            pst= con.prepareStatement("select * from product where id='"+PId+"' ");
            ResultSet Rs = pst.executeQuery();

            if(Rs.next()){
                txtsearch.setEditable(true);
                id2.setText(Rs.getString(1));
                txtpname.setText(Rs.getString(2));
                txtdes.setText(Rs.getString(3));
                txtbarcode.setText(Rs.getString(4));
                txtcprice.setText(Rs.getString(5));
                txtqty.setText(Rs.getString(6));
                txtrprice.setText(Rs.getString(7));
                txtlevel.setText(Rs.getString(8));

                txtsearch.setText("");
                jButton2.setEnabled(false);
                jButton4.setEnabled(true);
                jButton1.setEnabled(true);

            }
            else{
                JOptionPane.showMessageDialog(null, "That Product ID  does not exist");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }

    }//GEN-LAST:event_searchbtnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        df=(DefaultTableModel)jTable1.getModel();
        //
        int selected=jTable1.getSelectedRow();
        //      int id =Integer.parseInt(df.getValueAt(selected, 0).toString());
        id2.setText(df.getValueAt(selected, 0).toString());
        txtpname.setText(df.getValueAt(selected, 1).toString());
        txtdes.setText(df.getValueAt(selected, 2).toString());
        txtbarcode.setText(df.getValueAt(selected, 3).toString());
        txtcprice.setText(df.getValueAt(selected, 4).toString());
        txtqty.setText(df.getValueAt(selected,5).toString());
        txtrprice.setText(df.getValueAt(selected, 6).toString());
        txtlevel.setText(df.getValueAt(selected, 7).toString());
        jButton2.setEnabled(false);
        jButton1.setEnabled(true);
        jButton4.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //        df=(DefaultTableModel)jTable1.getModel();
        //
        //        int selected=jTable1.getSelectedRow();
        // int id =Integer.parseInt(df.getValueAt(selected, 0).toString());
        if(!(Pattern.matches("[0-9]*$", txtbarcode.getText()))){
            JOptionPane.showMessageDialog(null, "Please enter a valid phone number", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(!(Pattern.matches("[0-9][0-9._]*$", txtcprice.getText()))){
            JOptionPane.showMessageDialog(null, "Please enter a valid Cost Price", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(!(Pattern.matches("[0-9][0-9._]*$", txtcprice.getText()))){
            JOptionPane.showMessageDialog(null, "Please enter a valid Retail Price", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(!(Pattern.matches("[0-9][0-9._]*$", txtqty.getText()))){
            JOptionPane.showMessageDialog(null, "Please enter a valid Qty", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(!(Pattern.matches("[0-9][0-9._]*$", txtlevel.getText()))){
            JOptionPane.showMessageDialog(null, "Please enter a valid ReOderLevel", "Error", JOptionPane.ERROR_MESSAGE);}

        try {
            String  id=id2.getText();
            String  pname=txtpname.getText();
            String des=txtdes.getText();
            String barcode=txtbarcode.getText();
            String costprice=txtcprice.getText();
            String retailprice=txtqty.getText();
            String qty=txtrprice.getText();
            String arlevel=txtlevel.getText();

            pst=con.prepareStatement("update product set pname=?,description=?,barcode=?,cprice=?,rprice=?,qty=?,rlevel=? where id=?");
            pst.setString(1, pname);
            pst.setString(2, des);
            pst.setString(3, barcode);
            pst.setString(4, costprice);
            pst.setString(5, retailprice);
            pst.setString(6, qty);
            pst.setString(7, arlevel);
            pst.setString(8, id);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Product Updated");

            txtpname.setText("");
            txtdes.setText("");
            txtbarcode.setText("");
            txtcprice.setText("");
            txtqty.setText("");
            txtrprice.setText("");
            txtlevel.setText("");
            txtpname.requestFocus();
            load();
            autoID();

            jButton4.setEnabled(true);
            jButton4.setEnabled(true);

        } catch (SQLException ex) {
            Logger.getLogger(vendor.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        txtpname.setText("");
        id2.setText("");
        txtdes.setText("");
        txtbarcode.setText("");
        txtcprice.setText("");
        txtqty.setText("");
        txtrprice.setText("");
        txtlevel.setText("");

        txtpname.requestFocus();
        load();
        autoID();
        jButton2.setEnabled(true);
        jButton4.setEnabled(false);
        jButton1.setEnabled(false);
        if ((Pattern.matches("[0-9]*$", txtbarcode.getText())) || (Pattern.matches("", txtbarcode.getText())))
        {

            Border border = new LineBorder(Color.white, 2, true);
            txtbarcode.setBorder( border);

        }
        if ((Pattern.matches("[0-9][0-9._]*$", txtcprice.getText())) || (Pattern.matches("", txtcprice.getText())))
        {

            Border border = new LineBorder(Color.white, 2, true);
            txtcprice.setBorder( border);

        }
        if ((Pattern.matches("[0-9][0-9._]*$", txtcprice.getText())) || (Pattern.matches("", txtcprice.getText())))
        {

            Border border = new LineBorder(Color.white, 2, true);
            txtcprice.setBorder( border);

        }
        if ((Pattern.matches("[0-9]*$", txtrprice.getText())) || (Pattern.matches("", txtrprice.getText())))
        {

            Border border = new LineBorder(Color.white, 2, true);
            txtrprice.setBorder( border);

        }
          if ((Pattern.matches("[0-9]*$", txtqty.getText())) || (Pattern.matches("", txtqty.getText())))
        {

            Border border = new LineBorder(Color.white, 2, true);
            txtqty.setBorder( border);

        }
        if ((Pattern.matches("[0-9]*$",  txtlevel.getText())) || (Pattern.matches("",  txtlevel.getText())))
        {

            Border border = new LineBorder(Color.white, 2, true);
            txtlevel.setBorder( border);

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if( txtpname.getText().isEmpty() ||  txtdes.getText().isEmpty() ||  txtbarcode.getText().isEmpty() ||  txtcprice.getText().isEmpty()||  txtcprice.getText().isEmpty()||  txtrprice.getText().isEmpty()||  txtlevel.getText().isEmpty()  ){
            JOptionPane.showMessageDialog(null, "Please fill all the details", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(!(Pattern.matches("[0-9]*$", txtbarcode.getText()))){
            JOptionPane.showMessageDialog(null, "Please enter a valid phone number", "Error", JOptionPane.ERROR_MESSAGE);
                     }else if(!(Pattern.matches("[0-9][0-9._]*$", txtcprice.getText()))){
                    JOptionPane.showMessageDialog(null, "Please enter a valid Cost Price", "Error", JOptionPane.ERROR_MESSAGE);
                     }else if(!(Pattern.matches("[0-9][0-9._]*$", txtrprice.getText()))){
                    JOptionPane.showMessageDialog(null, "Please enter a valid Retail Price", "Error", JOptionPane.ERROR_MESSAGE);
                    }else if(!(Pattern.matches("[0-9]*$", txtqty.getText()))){
            JOptionPane.showMessageDialog(null, "Please enter a valid Qty", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(!(Pattern.matches("[0-9]*$", txtlevel.getText()))){
            JOptionPane.showMessageDialog(null, "Please enter a valid ReOderLevel", "Error", JOptionPane.ERROR_MESSAGE);}

        else{
            try {
                // TODO add your handling code here:
                String pname=txtpname.getText();
                String des=txtdes.getText();
                String barcode=txtbarcode.getText();
                String costprice=txtcprice.getText();
                String retailprice=txtcprice.getText();
                String qty=txtqty.getText();
                String rlevel=txtlevel.getText();
                String id=id2.getText();

                pst=con.prepareStatement("insert into product(id,pname ,description,barcode,cprice,rprice,qty,rlevel)values(?,?,?,?,?,?,?,?)");
                pst.setString(1,  id);
                pst.setString(2,  pname);
                pst.setString(3, des);
                pst.setString(4, barcode);
                pst.setString(5, costprice);
                pst.setString(6, retailprice);
                pst.setString(7, qty);
                pst.setString(8, rlevel);

                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Product added");

                txtpname.setText("");
                txtdes.setText("");
                txtbarcode.setText("");
                txtcprice.setText("");
                txtqty.setText("");
                txtrprice.setText("");
                txtlevel.setText("");

                txtpname.requestFocus();
                load();
                autoID();

            } catch (SQLException ex) {
                Logger.getLogger(vendor.class.getName()).log(Level.SEVERE, null, ex);
            }}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtlevelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlevelKeyReleased
        if ((Pattern.matches("[0-9]*$",  txtlevel.getText())) || (Pattern.matches("",  txtlevel.getText())))
        {

            Border border = new LineBorder(Color.white, 2, true);
            txtlevel.setBorder( border);

        }
        else
        {
            Border border = new LineBorder(Color.red, 2, true);
            txtlevel.setBorder( border);

        }
    }//GEN-LAST:event_txtlevelKeyReleased

    private void txtlevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlevelActionPerformed

    private void txtcpriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcpriceKeyReleased
        if ((Pattern.matches("[0-9][0-9._]*$", txtcprice.getText())) || (Pattern.matches("", txtcprice.getText())))
        {

            Border border = new LineBorder(Color.white, 2, true);
            txtcprice.setBorder( border);

        }
        else
        {
            Border border = new LineBorder(Color.red, 2, true);
            txtcprice.setBorder( border);

        }
    }//GEN-LAST:event_txtcpriceKeyReleased

    private void txtcpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcpriceActionPerformed

    }//GEN-LAST:event_txtcpriceActionPerformed

    private void txtcpriceMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcpriceMouseReleased

    }//GEN-LAST:event_txtcpriceMouseReleased

    private void txtbarcodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbarcodeKeyReleased
        if ((Pattern.matches("[0-9]*$", txtbarcode.getText())) || (Pattern.matches("", txtbarcode.getText())))
        {

            Border border = new LineBorder(Color.white, 2, true);
            txtbarcode.setBorder( border);

        }
        else
        {
            Border border = new LineBorder(Color.red, 2, true);
            txtbarcode.setBorder( border);

        }
    }//GEN-LAST:event_txtbarcodeKeyReleased

    private void txtbarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbarcodeActionPerformed

    }//GEN-LAST:event_txtbarcodeActionPerformed

    private void txtdesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdesActionPerformed

    private void txtpnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //        df=(DefaultTableModel)jTable1.getModel();
        //
        //        int selected=jTable1.getSelectedRow();
        //        int id =Integer.parseInt(df.getValueAt(selected, 0).toString());
        String id =id2.getText();
        try {
            pst=con.prepareStatement("delete from product where id=?");

            pst.setString(1, id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Product Deleted");

            txtpname.setText("");
            id2.setText("");
            txtdes.setText("");
            txtbarcode.setText("");
            txtcprice.setText("");
            
            txtrprice.setText("");
            txtqty.setText("");
            txtlevel.setText("");
            autoID();

            txtpname.requestFocus();
            load();
            jButton2.setEnabled(true);
        } catch (SQLException ex) {
            Logger.getLogger(vendor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtqtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtqtyKeyReleased
        if ((Pattern.matches("[0-9]*$", txtqty.getText())) || (Pattern.matches("", txtqty.getText())))
        {

            Border border = new LineBorder(Color.white, 2, true);
            txtqty.setBorder( border);

        }
        else
        {
            Border border = new LineBorder(Color.red, 2, true);
            txtqty.setBorder( border);

        }
    }//GEN-LAST:event_txtqtyKeyReleased

    private void txtqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqtyActionPerformed

    private void txtrpriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrpriceKeyReleased
        if ((Pattern.matches("[0-9][0-9._]*$", txtrprice.getText())) || (Pattern.matches("", txtrprice.getText())))
        {

            Border border = new LineBorder(Color.white, 2, true);
            txtrprice.setBorder( border);

        }
        else
        {
            Border border = new LineBorder(Color.red, 2, true);
            txtrprice.setBorder( border);

        }
    }//GEN-LAST:event_txtrpriceKeyReleased

    private void txtrpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrpriceActionPerformed

    private void txtrpriceMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtrpriceMouseReleased

    }//GEN-LAST:event_txtrpriceMouseReleased

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ProductID;
    private javax.swing.JLabel id2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField txtbarcode;
    private javax.swing.JTextField txtcprice;
    private javax.swing.JTextField txtdes;
    private javax.swing.JTextField txtlevel;
    private javax.swing.JTextField txtpname;
    private javax.swing.JTextField txtqty;
    private javax.swing.JTextField txtrprice;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
